### ISSUE TITLE
lerna run build failed

### ISSUE THREAD

**Issue by xiyanx** [scaljeri/chess.com#18] opened 2021-03-28 21:11 UTC
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@scaljeri/chess-shared' in 4.5s:
yarn run v1.22.4
$ rm -rf ./dist && tsc
Done in 4.21s.
lerna ERR! yarn run build exited 1 in '@scaljeri/chess-com-bot'
lerna ERR! yarn run build stdout:
yarn run v1.22.4
$ rm -rf ./dist && yarn build:frontend && yarn build:backend && yarn copy-api-worker
$ di -d -c tsc -b ./src -i shared frontend/main.ts -- -p tsconfig-frontend.json && yarn build:browserify
Glob file search: src\**\*.ts
Adding src/shared/environments/komodo.ts
Adding src/shared/game-play.ts
Adding src/shared/turn-observer.ts
Task skipped, content unchanged (src\frontend\main-di.ts)
Running: tsc -p tsconfig-frontend.json
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn tsc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn tsc',
  path: 'tsc',
  spawnargs: [ '-p', 'tsconfig-frontend.json' ]
}
error Command failed with exit code 1.
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@scaljeri/chess-com-bot'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

**Comment by scaljeri** [comment] 2021-03-29 08:29
It looks like you're on windows, duplicate of [this](https://github.com/scaljeri/chess.com/issues/13) issue

**Closed** 2021-12-27 21:13 UTC
Labels: duplicate
